# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
vi:
 languageCode: vi-VI
 contentDir: content/vi
 title: Vietnamese website title...
 params:
   description: Site description in Vietnamese...
 menu:
   main:
    - name: Home
      url: '#home'
      weight: 10
    - name: Overview
      url: '#projects'
      weight: 20
    - name: Publications
      url: '#featured'
      weight: 30
    - name: Events
      url: '#talks'
      weight: 40
    - name: News
      url: '#posts'
      weight: 50
    - name: Gallery
      url: '#gallery'
      weight: 60
    - name: Contact
      url: '#contact'
      weight: 70
